# Generated by Django 5.1.2 on 2024-10-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
