# Generated by Django 5.1.2 on 2024-10-14 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_note_cover_image_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır. En fazla 15 basamak olabilir.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
