# Generated by Django 5.1.2 on 2024-10-14 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_customuser_bio_remove_customuser_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır. En fazla 15 basamak olabilir.", regex='^\\+?[0-9]{9,15}$')]),
        ),
    ]
