# Generated by Django 5.1.2 on 2024-10-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_customuser_date_joined_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
