# Generated by Django 5.1.2 on 2024-10-15 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='area_of_use',
            field=models.CharField(blank=True, choices=[('school', 'Məktəb'), ('univers', 'Universitet'), ('documentary', 'Sənədlər'), ('blog', 'Blog'), ('translator', 'Tərcümə'), ('marketinq', 'Marketinq')], default='mekteb', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
