# Generated by Django 5.1.2 on 2024-10-15 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_customuser_area_of_use_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area_of_use',
            field=models.CharField(blank=True, choices=[('school', 'Məktəb'), ('university', 'Universitet'), ('documentary', 'Sənədlər'), ('blog', 'Blog'), ('translate', 'Tərcümə'), ('marketinq', 'Marketinq')], default='mekteb', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
