# Generated by Django 5.1.2 on 2024-10-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_alter_customuser_area_of_use_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
